import type { userType } from './types'

export const usersMockData: userType[] = [
	{
		id: 0,
		name: 'Alex Ca.',
		login: '@Alexy',
		isBest: true,
		avatar: '/src/entities/users/avatar0.png',
		cash: 8456,
		floorPrice: 3.5,
		owners: 2.2,
		items: 500,
	},
	{
		id: 1,
		name: 'Juliya Sa.',
		login: '@JuliyaS',
		isBest: true,
		avatar: '/src/entities/users/avatar1.png',
		cash: 5327,
		floorPrice: 7.9,
		owners: 3.4,
		items: 900,
	},
	{
		id: 2,
		name: 'Imrasts',
		login: '@imrasts',
		isBest: true,
		avatar: '/src/entities/users/avatar4.png',
		cash: 5231,
		floorPrice: 3.5,
		owners: 2.2,
		items: 500,
	},
	{
		id: 3,
		name: 'Liviya Ad.',
		login: '@Lia',
		isBest: true,
		avatar: '/src/entities/users/avatar2.png',
		cash: 9999,
		floorPrice: 3.5,
		owners: 2.2,
		items: 500,
	},
	{
		id: 4,
		name: 'Trevor Pu.',
		login: '@TrevorP',
		isBest: true,
		avatar: '/src/entities/users/avatar3.png',
		cash: 20,
		floorPrice: 3.9,
		owners: 3.4,
		items: 560,
	},
	{
		id: 5,
		name: 'Test T.',
		login: '@tested',
		isBest: true,
		avatar: '/src/entities/users/avatar4.png',
		cash: 5231,
		floorPrice: 3.5,
		owners: 2.2,
		items: 500,
	},
]
