// mockData - используется для заглушки backend api, чтобы данные так или иначе были

import type { nftType } from './types'

export const nftMockData: nftType[] = [
	{
		id: 0,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: '/src/entities/nfts/0.png',
		idOwner: 0,
	},
	{
		id: 1,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: '/src/entities/nfts/1.png',
		idOwner: 1,
	},
	{
		id: 2,
		name: 'NuEvey',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.25,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '19h 09m 12s',
		image: '/src/entities/nfts/2.png',
		idOwner: 2,
	},
	{
		id: 3,
		name: 'NuEvey',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.25,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '19h 09m 12s',
		image: '/src/entities/nfts/3.png',
		idOwner: 3,
	},
	{
		id: 4,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: '/src/entities/nfts/4.png',
		idOwner: 4,
	},
	{
		id: 5,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: '/src/entities/nfts/4.png',
		idOwner: 5,
	},
	{
		id: 6,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: '/src/entities/nfts/4.png',
		idOwner: 0,
	},
	{
		id: 7,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: '/src/entities/nfts/4.png',
		idOwner: 1,
	},
	{
		id: 8,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: '/src/entities/nfts/4.png',
		idOwner: 2,
	},
]
