// mockData - используется для заглушки backend api, чтобы данные так или иначе были

import avatar0 from '../0.png'
import avatar1 from '../1.png'
import avatar2 from '../2.png'
import avatar3 from '../3.png'
import avatar4 from '../4.png'
import type { nftType } from './types'

export const nftMockData: nftType[] = [
	{
		id: 0,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: avatar0,
		idOwner: 0,
	},
	{
		id: 1,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: avatar1,
		idOwner: 1,
	},
	{
		id: 2,
		name: 'NuEvey',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.25,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '19h 09m 12s',
		image: avatar2,
		idOwner: 2,
	},
	{
		id: 3,
		name: 'NuEvey',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.25,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '19h 09m 12s',
		image: avatar3,
		idOwner: 3,
	},
	{
		id: 4,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: avatar4,
		idOwner: 4,
	},
	{
		id: 5,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: avatar4,
		idOwner: 5,
	},
	{
		id: 6,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: avatar4,
		idOwner: 0,
	},
	{
		id: 7,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: avatar4,
		idOwner: 1,
	},
	{
		id: 8,
		name: 'Sun-Glass',
		description: 'none',
		royalty: 'Royalty',
		size: 253,
		tags: ['base'],
		currency: 'ETH',
		price: 1.75,
		stock: '001',
		sale: true,
		direct_sale: false,
		expirationDate: '07h 09m 12s',
		image: avatar4,
		idOwner: 2,
	},
]
